### PR TITLE
__call method refactoring

### PR DESCRIPTION
**Pull request by vitya1**
Partially reducing the magic method as a code smell. This version still compatible with old versions, but there will be necessary to change Client class signature to increase code readability.
PS: Sorry for the last PR failed tests

### CODE REVIEW

**Comment by vitya1** [comment]
Resolved conflicts

**Comment by thinkingserious** [comment]
@vitya1 what do you propose the new Client class signature to be?

**Comment by vitya1** [comment]
Thanks for your reviews @thinkingserious!
Probably it's good decision to use __call function to reduce code duplication. I just propose to increase the code readability and my way to do that is to avoid __call usages.
Maybe better to use neither __call nor function for each http method, but use a single function and pass http method name to that?
The underscore function has unclear name as my opinion (it is difficult to predict the method behavior by the name).

**Comment by thinkingserious** [comment]
@vitya1,

I think if people do not want to use the `__call` function, they can call `makeRequest` directly. The purpose of those magic functions is to allow for a fluent interface, please see this [blog post](https://sendgrid.com/blog/using-php-to-implement-a-fluent-interface-to-any-rest-api/).

I'm looking forward to your thoughts :)

**Comment by vitya1** [comment]
@thinkingserious,
Ok, maybe it not so bad to use __call. If you have decided to use it, I won't argue.

**Comment by thinkingserious** [comment]
Thanks @vitya1!

**Pull request closed without merging**
