### PR TITLE
Fix syntax errors in readme examples

### PR DESCRIPTION
**Pull request by michaelspiss**

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/php-http-client?pullRequest=52) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/php-http-client?pullRequest=52) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/php-http-client?pullRequest=52) it.</sub>

**Comment by mbernier** [comment]
Nice find!! Thank you.

**Comment by thinkingserious** [comment]
Hello @michaelspiss,<br /><br/>Thanks again for the PR!<br />                                              <br />We want to show our appreciation by sending                                              you some swag. Could you please fill out                                              <a href="https://dx.sendgrid.com/swag">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Comment by mbernier** [comment]
I want to add another comment. This is EXACTLY the kind of PR that I absolutely love. You just saved uncountable hours of frustration for every person who comes behind you - THANK YOU for finding this and fixing it.

**Pull request merged**
