### PR TITLE
implements sending concurrent requests with curl multi

### PR DESCRIPTION
**Pull request by lightbringer1991**
#hacktoberfest

This is an improvement as a partial answer to https://github.com/sendgrid/sendgrid-php/issues/259

Allow requests to be sent concurrently.

Works exactly like the single request, but use `curl_multi_` family.

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/php-http-client?pullRequest=24) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/php-http-client?pullRequest=24) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/php-http-client?pullRequest=24) it.</sub>

**Comment by thinkingserious** [comment]
This is awesome @lightbringer1991!

Could you please fix up the conflicts so we can merge? Thanks!

With Best Regards,

Elmer

**Comment by lightbringer1991** [comment]
hi, I have rebased with the latest master, could you please merge this PR, thank you.

**Comment by thinkingserious** [comment]
@caseyw, @vitya1, @Braunson, @cbschuld, @paoga87, @Taluu, @mazanax, @ninsuo, @ianh2, @WadeShuler,  @jaimehing, @KnightAR

If you have a moment, I'd appreciate some extra eyes on this EPIC PR :)

**Comment by thinkingserious** [comment]
@lightbringer1991

We have not been able to merge your Pull Request, but because you are awesome - we wanted to make sure you could still get a SendGrid Hacktoberfest shirt.  

Please go **fill [out our swag form](https://dx.sendgrid.com/swag) before Nov 5th** and we will send the shirt! (We know that you might have tried this before and it didn’t work, sorry about that!)

### **You have till Nov 5th to fill out this form** in order to get the Hacktoberfest shirt!

Thank you for contributing during Hacktoberfest! We hope to see you in the repos soon! Just so you know, we always give away a SendGrid shirt for your first ever non-Hacktoberfest PR that gets merged.

**Comment by ninsuo** [comment]
whoops, I was notified by GitHub and thought you talked to me, I filled the form 😅
don't take it into account haha

**Comment by thinkingserious** [comment]
No worries @ninsuo  :)

Thanks for the heads up!

**Comment by thinkingserious** [comment]
Hi @lightbringer1991,

Do you mind fixing these final conflicts so I can review and merge this in? Thank you!

With Best Regards,

Elmer

**Comment by lightbringer1991** [comment]
I have rebased with master, however, I cannot seem to fix all the code climate issues (toggle between complexity and multiple returns violation)
I'm not sure if the code complexity is so high that it is unmaintainable in this case, so maybe we can still merge it?

**Comment by thinkingserious** [comment]
Thank you @lightbringer1991!

I will review further and let you know my thoughts.

**Comment by thinkingserious** [comment]
Hello @lightbringer1991,<br /><br/>Thanks again for the PR!<br />                                              <br />We appreciate your contribution and look forward to                                              continued collaboration. Thanks!                                             <br /><br />Team SendGrid DX

**Pull request merged**
