### PR TITLE
Code climate config

### PR DESCRIPTION
**Pull request by misantron**
Issue #54

### CODE REVIEW

**Comment by misantron** [comment]
Code climate alerts seems strange. There are no whitespace at lines 82 and 86.
I'll try to fix it later.

**Comment by thinkingserious** [comment]
@misantron

We have not been able to merge your Pull Request, but because you are awesome - we wanted to make sure you could still get a SendGrid Hacktoberfest shirt.  

Please go **fill [out our swag form](https://dx.sendgrid.com/swag) before Nov 5th** and we will send the shirt! (We know that you might have tried this before and it didn’t work, sorry about that!)

### **You have till Nov 5th to fill out this form** in order to get the Hacktoberfest shirt!

Thank you for contributing during Hacktoberfest! We hope to see you in the repos soon! Just so you know, we always give away a SendGrid shirt for your first ever non-Hacktoberfest PR that gets merged.

**Comment by mbernier** [comment]
This is such a great change.  Thank you!

**Comment by thinkingserious** [comment]
Hello @misantron,<br /><br/>Thanks again for the PR!<br />                                              <br />We appreciate your contribution and look forward to                                              continued collaboration. Thanks!                                             <br /><br />Team SendGrid DX

**Comment by mbernier** [comment]
If you are interested, we would love the opportunity to talk to you about Hacktoberfest and our API libraries.

Our agenda would be: Explore what you liked and is there anything we can do to improve? 

You can grab a time [on my calendar](https://calendly.com/matt-bernier/30min) that works for you and we can have a chat on Google Hangout or Skype. If you prefer, you can email me using my GitHub username at my company’s domain.

Thank you so much,

Matt Bernier - @mbernier - SendGrid Developer Experience Product Manager
Elmer Thomas - @thinkingserious - SendGrid Developer Experience Engineer
@SendGrid

**Comment by misantron** [comment]
@thinkingserious @mbernier 
Thanks for your kind feedback. Hope i can make much more code improvements in near future.
I have another PR #53, there are some README and code example file fixes.
And i want to make an ussue about make client Response compatible with PSR-7 standart. It will be very useful i think.

**Pull request merged**
