### PR TITLE
#12 change from  to php union operator to combine curl options

### PR DESCRIPTION
**Pull request by emilva**
This should preserve the keys as expected.

### CODE REVIEW

**Comment by thinkingserious** [comment]
Hi @emilva!

Thanks for the PR!

Could you please take a moment to [sign our CLA](https://github.com/sendgrid/php-http-client/blob/master/CONTRIBUTING.md#cla) so we can review for merge?

Thanks!

**Comment by emilva** [comment]
Yes, just sent the CLA.

**Comment by thinkingserious** [comment]
Hi @emilva,

I can not find the CLA, did you send it to dx@sendgrid.com? From what email address did you send it?

Thanks!

**Comment by emilva** [comment]
resent now! should be from emilva@gmail.com

**Comment by ajbonner** [comment]
If there's any issues with the CLA, I'm happy to make a new PR and send a CLA in myself.

**Comment by thinkingserious** [comment]
@emilva, @ajbonner,

CLA received :)

As it stands right now, this one jumped to near the top of our backlog. We'll do our best to get this done ASAP.

**Comment by thinkingserious** [comment]
BTW @ajbonner, you are awesome for offering to make the PR and sign the CLA :)

**Comment by thinkingserious** [comment]
Thanks again @emilva!

Please fill out [this form](https://docs.google.com/forms/d/e/1FAIpQLSelP4uF-wGJebxVYq1DYw5WzHomEUauab3YiqrshyCkRs0fqw/viewform#start=invite) so we can send you some swag!

**Comment by emilva** [comment]
cool, thanks!

**Pull request merged**
