### PR TITLE
feat: Throw an InvalidRequest whenever a curl request fails

### LINKED ISSUE #90: Document and throw an error to help people with CURLOPT_SSL_VERIFYPEER issues
#### Issue Summary

If I try to send an email trough the sendgrid-php api I only get a timeout after a while, the email doesn't get send. There are no errors thrown. This issue happened after an update from version 3.9.0 to 3.9.1.

#### Steps to Reproduce

1. Try to send a simple email (from the sendgrid-php repository for example)

#### Technical details:

* php-http-client Version: 3.9.1 (commit 56d046a)
* PHP Version: 7.1.15-1

### PR DESCRIPTION
**Pull request by colinodell**
# Fixes #90

This is one of three possible solutions to #90. #104 is similar but doesn't use catchable exceptions, and #105 is more about avoiding the issue than notifying the user.

### Checklist
- [x] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [x] I have read the [Contribution Guide] and my PR follows them.
- [x] I updated my branch with the master branch.
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation about the functionality in the appropriate .md file
- [x] I have added in line documentation to the code I modified

### Short description of what this PR does:
- An exception will be thrown if a curl request fails due to something like SSL verification (**BC break**)
- Uses `composer/ca-bundle` (if installed) to locate the system's CA bundle or fall back to Mozilla's (#105)

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/php-http-client?pullRequest=103) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/php-http-client?pullRequest=103) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/php-http-client?pullRequest=103) it.</sub>

**Comment by thinkingserious** [comment]
Hello @colinodell,

I like this solution combined with #105. What do you see as the cons of choosing this solution to #104?

Thanks!

With Best Regards,

Elmer

**Comment by colinodell** [comment]
Hey Elmer,

I strongly prefer this option because any issues result in thrown exceptions which can be caught and dealt with.  The alternate approach in #104 cannot be caught and handled by anyone using this library, it just provides a better error message instead of failing silently.

The only potential con is that this is technically a backward-compatibility break as users of this library may not be expecting any exceptions to be thrown, so you'll probably want to bump the major version of this library if you're following [semver](https://semver.org/).  Despite this, I do think this approach is best way forward and it aligns with how other API libraries also throw expections when issues occur.

**Comment by thinkingserious** [comment]
Thanks @colinodell,

I agree with you. Please fold #105 into this PR. Thanks!

**Comment by colinodell** [comment]
Done!  I have also added some documentation via https://github.com/sendgrid/php-http-client/pull/103/commits/281048fb1a4733e71c86d3db917fbbee730521e4

**Comment by thinkingserious** [comment]
Hello @colinodell,<br /><br/>Thanks again for the PR!<br />                                              <br />It's <a href="https://sendgrid.com/blog/hacktoberfest-2018-has-arrived/">HACKTOBERFEST</a>! We want to show our appreciation by sending                                              you some special Hacktoberfest swag. If you have not already, could you please fill out                                              <a href="https://dx.sendgrid.com/hacktoberfest/join">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Comment by colinodell** [comment]
Done! Thanks for letting me know about that, I appreciate it!

**Comment by thinkingserious** [comment]
Hello @colinodell,<br /><br/>Thanks again for the PR!<br /><br />                                         We noticed that you have earned 3 out of the 5 points needed to receive glorious SendGrid Hacktoberfest swag.<br /><br />                                         Please take a moment to checkout <a href="https://dx.sendgrid.com/hacktoberfest/issues">this link</a> to find more issues to get you past the required threshold.<br /><br />                                         Also, please be sure that you have officially registered <a href="https://dx.sendgrid.com/hacktoberfest/join">here</a>.<br /><br />                                         Thank you and Happy Hacktobering!<br /><br />                                         Team SendGrid DX

**Comment by thinkingserious** [comment]
Hello @colinodell,<br /><br/>Thanks again for the PR!<br /><br />                                         You have earned 3 out of the 5 points needed to receive glorious SendGrid Hacktoberfest swag.<br /><br />                                         Please take a moment to checkout <a href="https://dx.sendgrid.com/hacktoberfest/issues">this link</a> to find more issues to get you past the required threshold or to simply continue the celebration.<br /><br />                                         Also, <strong>please be sure you have officially registered with us <a href="https://dx.sendgrid.com/hacktoberfest/join">here</a> by November 1, 2018</strong> to qualify.<br /><br />                                         If you have any questions you can email us at <a href="mailto:dx+hacktoberfest2018@sendgrid.com">dx+hacktoberfest2018@sendgrid.com</a>.<br /><br />                                         Thank you and Happy Hacktobering!<br /><br />                                         Team SendGrid

**Comment by alextech** [comment]
Is this the same or conflict with what I already have done at https://github.com/sendgrid/php-http-client/pull/99 ?

**Review by childish-sambino — APPROVED** [review]
LGTM

**Pull request merged**
