### PR TITLE
Library refactoring around PSR-2 / PSR-4 code standards

### PR DESCRIPTION
**Pull request by misantron**

### CODE REVIEW

**Comment by thinkingserious** [comment]
This is awesome @misantron!

Could you please sign our CLA so we can get it merged? https://github.com/sendgrid/php-http-client/blob/master/CONTRIBUTING.md#cla

**Comment by misantron** [comment]
Thanks for quick response.
Do i need an electronic signature for sign your CLA?

**Comment by misantron** [comment]
Any problems with PR merge?

**Comment by thinkingserious** [comment]
No problems @misantron, 

Just waiting for it to rise up through the queue for implementation.

It can move up the queue faster if others +1 or comment on this thread.

Thanks for checking in!

**Comment by thinkingserious** [comment]
@misantron,

Finally made it back to this ticket :)

Could you please take a moment to check out the merge conflicts?

**Comment by misantron** [comment]
Branch is up to date now and has no conflicts

**Comment by thinkingserious** [comment]
Awesome, thanks! There are just a few more tickets ahead of this one now.

**Comment by thinkingserious** [comment]
Hello @misantron,

I am trying to test out this code before I merge and I have run into an issue.

First I ran `composer install`

In the root directory, I created a test.php file with the folloiwng code:

```php
<?php
include('./lib/Client.php');
$apiKey = getenv('SENDGRID_API_KEY');
$headers = ['Authorization: Bearer ' . $apiKey];
$client = new SendGrid\Client('https://api.sendgrid.com', $headers, '/v3');

// GET Collection
$response = $client->api_keys()->get();
echo $response->statusCode();
echo $response->body();
echo $response->headers();
```

When I try to run with `php test.php` I get the following error:

```php
Fatal error: Class 'SendGrid\Response' not found in /Users/thinkingserious/Workspace/sendgrid/php-http-client/lib/Client.php on line 128
```

**Comment by misantron** [comment]
You must include SendGrid\Response class file too or use class autoloader generated via Composer.
```php
include('./lib/Response.php');
```
or
```php
require 'vendor/autoload.php';
```

**Pull request merged**
